sudo: false
language: node_js
node_js:
  - 5.0.0
sudo: false
before_script:
- npm i
script:
- npm test
env:
  global:
  - secure: Qfhaop3FD6ECsC5wCOePcJilTh9bcklqhqn865UAR65XaBGTgrHuMx1rTTHNVSHDFvdvcW8VvE+G0AtFSoejzU1BBxTF4LRFsMEm0U8DDlKhgtFQYzZ8eKS1KAMkl0U85+es32spzim5liI8emrQ6UKEM+LU0byeyaXrHQAavcVhSOfts3b1iUhEZ2TPU9KEroPQ4c2SvljeHvYeN/uhjApHIf8e3JEHYepNbs/ZbAlY971LwGTyoBWhGQEGQ+c/PlywpiuL+NeSMMDIUkdiW9IESJhqwE2pT2lldxI/CIy9A58ZUeuq0GTc3uStr59XnKaowuO4/LhPx5wl+HZmA0zqOrFPAw8GKES6/4IJj09gRQ3kQceQ9cXUgdUwRGtl54haQr5v2w9x+o6o24iMuOO6SxotvDjwnlUEvqhb/yWKi5h42qmN8L8dFf5s40ZapwgouC9nwdZCdsN10bycHqT1MOlTjaX7iIu9q2JVwwmfcCUj4ut51jFzHRCROe4foxq6zmWxmnN3finVES66KSl7k0g6vaMVrlmWz7n5hZDG4kYSLmWOuBNBmjzql701Z88Dcl+4sae/EJbIIGBMdR1cMV6/bZM6KPQBIJRqwMU0XJiPfFi1/TQZQ76V4ElE2bLgH16e8dpfOHuRs9jzVH6UUgft2os/GozJfoOT6Bk=
  - secure: bv4mwPb3Jmm+Xw2ODE3tu/DwhNqfyI7pBk4aVYlbHjbFSbrnzrS65n6mlz2vfpTTs7zwHXgXlsyhs/N78ITgSLkRPcsOSNsEMzInK+IICEEksnWCyayxf6JFwQGUAgSRMDuOauedvtILOxtW7qvPkrpl3vDj27Z9oa23fWn6zu9bawFYdbcfgws+WEmRnOl3sy7xG9iZJuWO/MXf9nCLtuqHLCVYGq4v2LiIQZCYqMdedutkt3ZkHYus8kgzFmvGY48AnqG3BuaJ5Xl69TjiJzbokIzrTzQUzFb/YQw7QmSEtCBBobcLOdqjx+jvKX574Luh1QIQJ3lwOzj7SWwSPDnXVqoxYWDbMWeFWmDgam7l8ehSWgjDIC1ogX32526YoIV8Lzeosi1Jeo7w7wDyR91vqd1/vr/+9Zmew7TDtKMn8l3K4qXVe+Exds0G1Y9d2LiGU1Cj0DxxDfnV1aBXFjbkLEnoxy2BvhjEwkMs53hDjIn+BVxccWQDNHh3aZ5wTgDyXpokxtm9dNv+u5zYzm0lu7B6TGjXAvMlxarLEOHxVHeu7PniZvoJjqZREoTGdazJa+wOz+UaOOItITci1CL8onj3H97zPce7lVB+qFn2nkRADh0IoOc3xwrXTW3W8Y33pCOmD+wjcHza9/0HNcICuKKORF20wZwXpj9G7cc=
cache:
  bundler: true
  directories:
  - node_modules
before_deploy: pip install --user awscli
deploy:
  provider: script
  script: ~/.local/bin/aws s3 sync deploy s3://morgondag/kim-site/ --region=eu-west-1 --delete
  skip_cleanup: true
  on:
    branch: master
